name: Build N64 ROM
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build with Libdragon
        uses: dragonminded/libdragon@main
        with:
          run: |
            libdragon-cc -o my_game.elf main.c
            libdragon-romstage -o my_game.z64 my_game.elf

      - name: Upload ROM Artifact
        uses: actions/upload-artifact@v4
        with:
          name: n64-rom
          path: "my_game.z64"
